# Project Information
site_name: CHARLIE (Circrnas in Host And viRuses anaLysis pIpEline)
site_author: Vishal Koparde, Ph.D.
# Repository
repo_name: CCBR/CHARLIE
repo_url: https://github.com/CCBR/CHARLIE
edit_uri: https://github.com/CCBR/CHARLIE/edit/main

# Copyright
copyright: Copyright &copy; 2023-{{ now().year }} CCR Collaborative Bioinformatics Resource

# Configuration
theme:
  name: readthedocs
  locale: en
  custom_dir: docs/overrides
  #
# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCBR
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories
  # version:
  #   provider: mike

extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - Home: index.md
  - Workflow: flowchart.md
  - Tutorial: tutorial.md
  - References: references.md
  - Changelog: CHANGELOG.md
  - How to contribute: contributing.md
