#!/usr/bin/env bash
snakemakelog=$1
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
${SCRIPT_DIR}/jobby $(grep --color=never "^Submitted .* with external jobid" $snakemakelog | awk '{{print $NF}}'  | sed "s/['.]//g" | sort | uniq | tr "\\n" " ")