#!/usr/bin/env bash

if [ "$#" != "1" ];then
    echo "Provide a TAG as argument!"
    exit
fi

# Needs changing as we are pushing to GHCR

dockerhub_account="nciccbr" 
# dockerhub_account is same as "ghcr.io/<NAMESPACE>" on ghcr
# foldername is the reponame
# echo $GH_PAT | docker login ghcr.io -u $GH_USERNAME --password-stdin
CWD=`pwd`
JUSTFOLDERNAME=$(basename $CWD)
reponame="$JUSTFOLDERNAME"

dt=$(date +"%y%m%d")
tag="$1"

echo "Pushing ${dockerhub_account}/${reponame}:${tag} ... "
docker push ${dockerhub_account}/${reponame}:${tag}
echo "making ${tag} the \"latest\" tag ..."
docker tag ${dockerhub_account}/${reponame}:${tag} ${dockerhub_account}/${reponame}:latest
echo "Pushing ${dockerhub_account}/${reponame}:latest ..."
docker push ${dockerhub_account}/${reponame}:latest